# Dev overrides for contrastive learning

data:
  batch_size: 2
  num_workers: 0

training:
  max_epochs: 2
  limit_train_batches: 2
  limit_val_batches: 2
  limit_test_batches: 2
  log_every_n_steps: 1
  accumulate_grad_batches: 4

model:
  reconstruction:
    enable: true
    loss_weight: 0.001
    target_frame_size: 64
    num_reconstruct_frames: 4


wandb:
  enabled: false
