# Dev overrides for linear probing

data:
  batch_size: 1
  num_workers: 0

training:
  max_epochs: 2
  limit_train_batches: 10
  limit_val_batches: 10
  limit_test_batches: 10
  log_every_n_steps: 1
