# Dev overrides for linear probing

data:
  batch_size: 16
  num_workers: 0

training:
  max_epochs: 2
  limit_train_batches: 1.0
  limit_val_batches: 2
  limit_test_batches: 2
  log_every_n_steps: 1

wandb:
  enabled: false
