name: video_actor_contrastive

video_encoder_cfg:
  model_type: siglip
  freeze_backbone: true

video_key: video
aux_keys: null

head_hidden_sizes: [256, 256]
activation_class: torch.nn.Tanh
dropout: 0.0
return_temporal_features: false

# Contrastive projector settings
projector_hidden_sizes: [512]
projector_out_dim: 256
projector_key: proj_embedding
use_logit_scale: true
use_logit_bias: true
logit_scale_init: 1.0
