meta:
  task: enemy_location_nowcast
  fast_dev_run: false
  resume_exp: null
  exp_name: enemy-nowcast
  run_name: enemy-nowcast-clip

data:
  labels_filename: enemy_location_nowcast_s1s_l5s.csv # CSV with player locations

wandb:
  group: '${meta.exp_name}'
  tags: ['${meta.exp_name}']
  notes: 'enemy location nowcast'
