meta:
  task: teammate_location_nowcast
  fast_dev_run: false
  resume_exp: null
  exp_name: teammate-location-nowcast
  run_name: teammate-location-nowcast-clip

data:
  labels_filename: teammate_location_nowcast_s1s_l5s_half.csv  # CSV with teammate location labels

wandb:
  group: '${meta.exp_name}'
  tags: ['${meta.exp_name}']
  notes: 'teammate location nowcast'
